WORKSHOP_NAME=quay
WORKSHOP_IMAGE=quay.io/redhatgov/quay-workshop:latest
WORKSHOP_TITLE="Quay Workshop V1"
WORKSHOP_DESCRIPTION="Quay Workshop V1"
RESOURCE_BUDGET=medium
MAX_SESSION_AGE=3600
IDLE_TIMEOUT=300
