#!/bin/bash

# This 'setup' script is where you can add steps that should be run each
# time the container for the workshop is started. Note that if you are
# using persistent storage with a workshop and make changes to files from
# this script, or are deploying applications, your scripts must cope with
# the steps having already been run. This is because this script will be
# run a second time if the container were restarted for some reason.
namespace=quay
read user < <(oc project --short)
oc login -u opentlc-mgr -p r3dh4t1!
#Create new namespace
cat << EOF | oc apply -f -
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: $namespace
spec: {}
EOF
#Install the Quay Operator
cat <<EOF | oc apply -f -
# Base namespace for creation of operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-enterprise-operatorgroup
  namespace: $namespace
spec:
  targetNamespaces:
  - $namespace
# Subscription to trigger OLM installation
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: $namespace
spec:
  channel: quay-v3.3
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# Secret required to pull from quay.io
EOF
cat <<EOF | oc apply -f -
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: $namespace
spec:
  hard:
    configmaps: "10" 
    persistentvolumeclaims: "6" 
    replicationcontrollers: "15" 
    secrets: "50" 
    services: "10"
EOF
oc adm policy add-role-to-user admin system:serviceaccount:homeroom:$user -n $namespace
oc login -u system:serviceaccount:homeroom:$user
oc project $namespace
