#!/bin/bash

# This 'setup' script is where you can add steps that should be run each
# time the container for the workshop is started. Note that if you are
# using persistent storage with a workshop and make changes to files from
# this script, or are deploying applications, your scripts must cope with
# the steps having already been run. This is because this script will be
# run a second time if the container were restarted for some reason.
namespace=quay-workshop
oc project --short > output.txt
#echo "user=`oc project --short`" > var.sh
#. var.sh
user=$(oc project --short)
echo $user >> output.txt
#read user < <(oc project --short)
oc login -u opentlc-mgr -p r3dh4t1!
#Install the Quay Operator
#Create New Workspace
cat << EOF | oc apply -f -
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: $namespace
spec: {}
EOF
cat << EOF | oc apply -f -
# Base namespace for creation of operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-enterprise-operatorgroup
  namespace: $namespace
spec:
  targetNamespaces:
  - $namespace
# Subscription to trigger OLM installation
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: $namespace
spec:
  channel: quay-v3.3
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# Secret required to pull from quay.io
EOF
oc adm policy add-role-to-user admin system:serviceaccount:homeroom:$user -n $namespace >> output.txt
oc adm policy remove-user system:serviceaccount:homeroom:$user -n $user >> output.txt
oc login -u system:serviceaccount:homeroom:$user >> output.txt
oc project $namespace >> output.txt
